server:
  port: 8080

jwt:
  secret: "tmakdlfrpdlxm"
  # 스마일게이트

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/auth?useSSL=false&serverTimezone=Asia/Seoul
    #    url: jdbc:mysql://localhost:3306/meeting?serverTimezone=Asia/Seoul
    username: alstmdsha
    password: min753951
    driver-class-name: com.mysql.jdbc.Driver


